headers = [
    "file_name",
    "business_name",
    "business_address",
    "country",
    "address",
    "date",
    "time",
    "payment_method",
    "total",
    "product_quantity",
    "subtotal",
    "tax",
    "product_type",
]